// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppzctdbyanfoaavvufyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwemN0ZGJ5YW5mb2FhdnZ1ZnlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTA1NDksImV4cCI6MjA2NTc2NjU0OX0.KTyw_qv2WlFZGx6clr3hmoTpLb49YwhcetbK3mRi1nI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);